Origin/sign up
cefariron/diamond_code_team pull request #14
Opened 2023-09-10 14:42 UTC by And1An

2023-09-10 18:11 UTC, cefariron requested changes
Очень замусоренный код, читай коменты, чисти, исправляй ошибки, присылай на проверку

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +
удали все лишние пустые рядки, отступ между павилами 1 рядок

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +}
колор и фонт фемили бесполезный код, это указано в глобальных стилях, удалить. леттер спейсинг указать в em

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +}
лишний код, он ничего не делает

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +}
в спане обозначаешь только цвет, обозначаешь через переменную, указанную в глобальных стилях

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +}
леттер спейсинг указать в em

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +}
послетого как в спане оставил только цвет, удали полностью это бесполезное правило

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +}
колор, фонт фемили и фонт вейт бесполезный код. леттер спейсинг указать в em

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +        letter-spacing: -0.32px;
колор, фонт стайл и фонт вейт бесполезный код. леттер спейсинг указать в em

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +}
бекграунд колор и колор указывай через переменную, указанную в глобальных стилях. опасити нужно задать на псевдокласс .sign-up-section-form-input::placeholder, здесь он не нужен

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +}
собери это в одно цсс правило, добавь ховер, и удали колор, он здесь не нужен

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +}
задай одинаковые значения 8 и 14, не прикалывайся, и собери эти 4 правила в два, засоряешь код

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +}
убрать марджин, он здесь ВООБЩЕ не нужен

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +}
убрать марджин, он здесь ВООБЩЕ не нужен

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +}
удалить, бесполезный код

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +}
фонт фемили - бесполезный код. бэкграунд колор указываешь переменной

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +}
здесь не нужен макс видз, кнопка ограничивается контейнером формы, к которой ты уже применил ранее макс видз 480, а к кнопке видз 100%

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +   }
фонт фемили и фонт вейт удалить, бесполезный код

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +}
фонт фемили и фонт вейт удалить, лишний код. ворд спейсинг тоже, не указан в макете

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +}
удалить, бесполезный код. этот контейнер у тебя и так блоковый, направление оси Х идет сверху вниз

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +}
цвет указывай переменной с глобал стайл

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +}
Пока не буду ничего говорить о методе позицонирования картинки, об этом позже

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +}
Пока не буду ничего говорить о методе позицонирования картинки, об этом позже

2023-09-10 18:11 UTC, cefariron commented on src/css/sign-up.css
> +}
бекграунд колор задай переменной

2023-09-11 06:59 UTC, closed without merging

2023-09-11 11:28 UTC, And1An commented on src/css/sign-up.css
> +}
удалил

2023-09-11 11:28 UTC, And1An commented on src/css/sign-up.css
> +}
поставил

2023-09-11 11:28 UTC, And1An commented on src/css/sign-up.css
> +}
поставил

2023-09-11 11:33 UTC, And1An commented on src/css/sign-up.css
> +}
поставив

2023-09-11 11:34 UTC, And1An commented on src/css/sign-up.css
> +}
есть

2023-09-11 11:35 UTC, And1An commented on src/css/sign-up.css
> +}
удалил

2023-09-11 11:36 UTC, And1An commented on src/css/sign-up.css
> +}
color + 
font удалил 
летер спейсинг поставил

2023-09-11 11:40 UTC, And1An commented on src/css/sign-up.css
> +
сделал +